//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GACManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GACManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to install the assembly - it is not strongly named..
        /// </summary>
        internal static string ErrorMsg_InstallationFailed_AssemblyIsNotStrongNamed {
            get {
                return ResourceManager.GetString("ErrorMsg_InstallationFailed_AssemblyIsNotStrongNamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to install the assembly..
        /// </summary>
        internal static string ErrorMsg_InstallationFailed_GenericError {
            get {
                return ResourceManager.GetString("ErrorMsg_InstallationFailed_GenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To install assemblies you should run GAC Manager as administrator..
        /// </summary>
        internal static string ErrorMsg_InstallationFailed_UnauthorizedError {
            get {
                return ResourceManager.GetString("ErrorMsg_InstallationFailed_UnauthorizedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: cannot uninstall this assembly - it has already been uninstalled..
        /// </summary>
        internal static string ErrorMsg_Uninstall_AlreadyUninstalled {
            get {
                return ResourceManager.GetString("ErrorMsg_Uninstall_AlreadyUninstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: cannot uninstall this assembly - it has has a delete pending..
        /// </summary>
        internal static string ErrorMsg_Uninstall_Deleting {
            get {
                return ResourceManager.GetString("ErrorMsg_Uninstall_Deleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: cannot uninstall this assembly - it is in use..
        /// </summary>
        internal static string ErrorMsg_Uninstall_InUse {
            get {
                return ResourceManager.GetString("ErrorMsg_Uninstall_InUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: cannot uninstall this assembly - cannot find the assembly..
        /// </summary>
        internal static string ErrorMsg_Uninstall_NotFound {
            get {
                return ResourceManager.GetString("ErrorMsg_Uninstall_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: cannot uninstall this assembly - it was installed as part of another product..
        /// </summary>
        internal static string ErrorMsg_Uninstall_PartOfAnotherProduct {
            get {
                return ResourceManager.GetString("ErrorMsg_Uninstall_PartOfAnotherProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To remove assemblies from GAC you should run GAC Manager as administrator..
        /// </summary>
        internal static string ErrorMsg_Uninstall_UnauthorizedError {
            get {
                return ResourceManager.GetString("ErrorMsg_Uninstall_UnauthorizedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: failed to uninstall assembly..
        /// </summary>
        internal static string ErrorMsg_Uninstall_Unknown {
            get {
                return ResourceManager.GetString("ErrorMsg_Uninstall_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GacUtil is installed.
        /// </summary>
        internal static string Msg_GacUtilFound {
            get {
                return ResourceManager.GetString("Msg_GacUtilFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find GacUtil.
        /// </summary>
        internal static string Msg_GacUtilNotFound {
            get {
                return ResourceManager.GetString("Msg_GacUtilNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The assembly was installed succesfully!.
        /// </summary>
        internal static string Msg_InstallationCompleted_Success {
            get {
                return ResourceManager.GetString("Msg_InstallationCompleted_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Assemblies....
        /// </summary>
        internal static string Msg_RefreshAssemblies_Progress {
            get {
                return ResourceManager.GetString("Msg_RefreshAssemblies_Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded {0} assemblies in {1} milliseconds.
        /// </summary>
        internal static string Msg_RefreshAssemblies_Success {
            get {
                return ResourceManager.GetString("Msg_RefreshAssemblies_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: the assembly was uninstalled successfully..
        /// </summary>
        internal static string Msg_Uninstall_Success {
            get {
                return ResourceManager.GetString("Msg_Uninstall_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/PonyMan/GACManager.
        /// </summary>
        internal static string ProjectHomePageUrl {
            get {
                return ResourceManager.GetString("ProjectHomePageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Assembly to Install.
        /// </summary>
        internal static string Prompt_Installation_SelectAssembly {
            get {
                return ResourceManager.GetString("Prompt_Installation_SelectAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to uninstall selected assemblies?.
        /// </summary>
        internal static string Prompt_Uninstall {
            get {
                return ResourceManager.GetString("Prompt_Uninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        internal static string Title_Install {
            get {
                return ResourceManager.GetString("Title_Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        internal static string Title_Uninstall {
            get {
                return ResourceManager.GetString("Title_Uninstall", resourceCulture);
            }
        }
    }
}
